---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: _layouts
  label: Layouts
  create: all
  match: "**/*"
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: bundle install && gem install -n /usr/local/bin jekyll
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --config _config.yml,_config-dev.yml
